apiVersion: v1
kind: Service
metadata:
  name: python-hello-service
  namespace: test38  # Specify the namespace
spec:
  selector:
    app: python-hello  # Match pods with the label app=python-hello
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8080  # Port on the container
  type: ClusterIP  # Default service type (accessible only within the cluster)
